# Mago configuration file
# For more information, see https://mago.carthage.software/#/getting-started/configuration
php_version = "7.4.0"

[source]
paths = ["src/"]
includes = ["vendor", "constant.php", "../../../wp-admin", "../../../wp-includes", "../../../index.php", "../../../wp-activate.php", "../../../wp-blog-header.php", "../../../wp-comments-post.php", "../../../wp-config-sample.php", "../../../wp-cron.php", "../../../wp-links-opml.php", "../../../wp-load.php", "../../../wp-login.php", "../../../wp-mail.php", "../../../wp-settings.php", "../../../wp-signup.php", "../../../wp-trackback.php", "../../../xmlrpc.php"]
excludes = []

[format]
print_width = 120
tab_width = 4
use_tabs = false

[linter]
default_plugins = true
plugins = ["symfony"]